#!/bin/bash
#create PNG image with transparent background, bright waveform
#output can be used with playblack.js sticky player

#script reads file uris from stdin (absolute path)

#where to write images
WAVE_OUT_DIR="/tmp"

#directory where this script is stored
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#cd "$DIR" || exit 1

#expect script in same dir
ls "${DIR}/create_waveform.sh" >/dev/null 2>&1 
if [ $? -ne 0 ]; then 
	echo "create_waveform.sh script not found.">&2; exit 1; fi

#if [ $# -ne 1 ]; then 
#	echo "need args: audio_in">&2; exit 1; fi

#infile="$1"

#write header
cat - << _EOF_
/*javascript generated by create_playitem.sh*/
var get_playitems=function() {
return { "items": [
_EOF_

#process every line on stdin (... | create_playitem.sh ...)
while read line; do
infile="$line"

###tools check
outname="`echo "$infile"|base64 -w0 -`.png"
outfile="${WAVE_OUT_DIR}/${outname}"

#echo "${DIR}/create_waveform.sh $infile $outfile"
"${DIR}/create_waveform.sh" "$infile" "$outfile"
if [ $? -eq 0 ]; then
#exit 1; fi
cat - << _EOF_
{
	"audio": "file://${infile}"
	, "wave": "file://${outfile}"
},
_EOF_
else
	echo "skipping file!">&2;
fi

#for every input line
done

#close output
cat - << _EOF_
]};};
/*EOF*/
_EOF_
#EOF
